-- ============================================================
-- nessoo_admin_app — least-privilege Postgres role
--
-- THIS FILE IS NOT THE SOURCE OF TRUTH. The grants are defined once, in
-- scripts/create-admin-role.mjs, and applied from there:
--
--   ADMIN_DB_URL=<privileged>  ADMIN_APP_PASSWORD=<secret> \
--   node scripts/create-admin-role.mjs --confirm
--
-- This file used to carry a second, hand-maintained copy of every GRANT. Two
-- copies of a grant list drift, and a drifted grant list is how a column ends up
-- exposed without anyone noticing — the same failure mode as the missing
-- `session` grant that took down the dashboard on first load. So the list lives
-- in one place and this file explains the reasoning behind it.
--
-- ── Design rules ────────────────────────────────────────────
--
-- 1. No path to credentials. No grant of any kind on `session` beyond three
--    timestamp columns, and none at all on `account`, `verification`,
--    `application_tokens` or `org_invite_links` — each holds bearer material.
--    Session validation goes through validate_admin_session() (homey-ux
--    migration 0027), which is SECURITY DEFINER, so the role gets EXECUTE and
--    never SELECT on the underlying tables.
--
-- 2. No path to regulated PII. renter_profiles excludes ssn_encrypted,
--    dob_encrypted, credit_score, phone, address and commute_destination.
--
-- 3. Column allowlists everywhere, no whole-table reads. This is what makes a
--    future `ALTER TABLE ... ADD COLUMN` invisible to this role by default
--    rather than automatically readable. It also keeps landlord contact details
--    (units.landlord_name/email/phone) and Stripe identifiers out of a console
--    that never displays them.
--
-- 4. No DELETE anywhere, and no UPDATE outside properties/units. Both use
--    soft-deletes (deleted_at) throughout homey-ux; a hard DELETE would diverge
--    from that convention and cascade.
--
-- 5. audit_events is INSERT-only. The console writes the audit trail; it has no
--    business reading back every actor's IP address and metadata platform-wide.
--
-- ── Verifying ───────────────────────────────────────────────
--
--   npm run verify:role   asserts each forbidden read fails with 42501 and each
--                         needed one succeeds — run it AS the role
--   npm run smoke         runs every query the app actually makes
--
-- Run both before deploying. verify:role alone is not enough: its "allowed" list
-- is hand-written, and an app query it happens not to cover can still fail in
-- production.
--
-- ── Maintenance ─────────────────────────────────────────────
--
-- When a query in lib/queries/*.ts starts reading a new column, add that column
-- to COLUMN_GRANTS in scripts/create-admin-role.mjs and re-run it. The script is
-- idempotent and revokes everything first, so re-running can genuinely tighten a
-- grant, not only widen it.
--
-- Re-running does NOT touch the role or its password by default — on RDS,
-- ALTER ROLE ... NOSUPERUSER requires actual superuser and fails. Pass
-- --rotate-password to change the password.
-- ============================================================
